### ISSUE TITLE
open gis data resources 

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/geofi#15]
Shall we create a list of open FI geodata resources that could be incorporated or otherwise relevant? In issues, in vignette, or elsewhere in the docs.

Some resources:
-  [gisdata collected by](https://github.com/teelmo/geodata) @teelmo

**Comment by jlehtoma** [comment]
Several already exist, e.g. the one by [the Finnish Geospatial Research and Education Hub](http://www.geoportti.fi): http://www.geoportti.fi/data/find-and-get-data/

Still, might be useful to link to these and/or link some of the less well-known ones.

**Comment by antagomir** [comment]
Related to #25

**Comment by antagomir** [comment]
Merged with #25
