### ISSUE TITLE
Rename wfs()?

### ISSUE THREAD

**Issue by jlehtoma** [rOpenGov/geofi#16]
I don't recall our last discussion on the function naming conventions exactly, but I don't think [`wfs()`](
https://github.com/rOpenGov/geofi/blob/e2a38a9a733d83d8c57a7b37c39c9f1abfdc474e/R/wfs.R#L17) is a very good name for the function after all. To me, `wfs` implies an abstraction of a WFS, which is what the different classes and methods in `ows4R` do. `wfs()` is rather a generic getter function for data available through a WFS, so maybe `get_wfs_layer()` etc. would be better. Any comments?

**Comment by antagomir** [comment]
Fine

**Comment by jlehtoma** [comment]
Done in `devel`-branch.
