### ISSUE TITLE
Visualizing certain values with a color on a map

### ISSUE THREAD

**Issue by Liisukas** [rOpenGov/geofi#30]
Hi!

Could you tell me if it is possible to visualise something like the following picture with your library?

![image](https://user-images.githubusercontent.com/50153435/98379850-75289b00-2050-11eb-9766-da0c45d3e49b.png)

**Comment by antagomir** [comment]
Something along these lines should be possible but geofi is focusing on Finnish maps.

Have you checked the example tutorials under the Articles tab at [geofi website](https://ropengov.github.io/geofi/)?
