### ISSUE TITLE
Hyvinvointialueet

### ISSUE THREAD

**Issue by muuankarski** [rOpenGov/geofi#40]
Will implement these manually for 2021

- https://soteuudistus.fi/mika-on-hyvinvointialue
- https://fi.wikipedia.org/wiki/Hyvinvointialue
- https://vaalit.fi/hyvinvointialueet

Missing translations, though

**Comment by muuankarski** [comment]
First version of the manual implementation here both in Finnish and Swedish
https://github.com/rOpenGov/geofi/commit/77399fa15f82bbf77a0c58830c45f41e8dc7490e

Please test if you are interested! Will release in CRAN next week after some holidays.


```r
library(remotes)
install_github("ropengov/geofi", ref = "devel")
library(geofi)
library(dplyr)
library(sf)
library(ggplot2)

muni <- get_municipalities(year = 2021)
muni %>% 
  count(hyvinvointialue_name_fi,hyvinvointialue_name_sv,hyvinvointialue_code) %>% 
  ggplot(aes(label = hyvinvointialue_name_sv,fill = hyvinvointialue_code)) +
  geom_sf() + theme(legend.position = "none") +
  geom_sf_text()

```

**Comment by antagomir** [comment]
Works for me at least, after loading the libraries geofi, dplyr, ggplot2
