### ISSUE TITLE
WFS connection

### ISSUE THREAD

**Issue by rondon-d** [rOpenGov/geofi#48]
Hello!
I am trying to build some maps, but I am getting the following error: 

![image](https://github.com/rOpenGov/geofi/assets/145334565/73e2ce43-cccf-48eb-81e3-6ae840395096)

I have no clue on how to proceed here, or what is going on.  
any help will be very useful!

Thank you

**Comment by muuankarski** [comment]
Hi @rondon-d , could you try again now? There has been some issues with server availability at Statistics Finland in last few days. I assume that your issue is due to that, too.

**Comment by pitkant** [comment]
The query worked for me. It could be a temporary problem or, as the error message says, a problem with your organisations firewall/proxy settings. Have you tried doing the query again?

**Comment by rondon-d** [comment]
Hello,
sorry for the late response. 
It seems to be working now 👍 
Thanks for your time!
