### ISSUE TITLE
Ternary colors plots?

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/geofi#8]
Ternary color plots would be a very nice addition to gisfin set. @janikmiet has implemented [this](https://github.com/ikashnitsky/the-lancet-2018) for [Finnish maps](https://twitter.com/janikmiet/status/1024923420314820609). See also [Github](https://twitter.com/ikashnitsky/status/1020257091574018048).

**Comment by janikmiet** [comment]
Package _tricolore_ is needed for ternary color plots. Started writing a vignette for this which is based on current vignette.

**Comment by antagomir** [comment]
Great!

**Comment by jlehtoma** [comment]
As far as I could tell, this is now implemented [here](https://github.com/rOpenGov/geofi/blob/master/vignettes/tricolore_tutorial.Rmd). Is it ok to close this issue?

**Comment by janikmiet** [comment]
Yes, issue can be closed. I don't have rights to do that.

**Comment by muuankarski** [comment]
@janikmiet Could you have a look at the vignette? The [last code chunk](https://github.com/rOpenGov/geofi/blob/master/vignettes/tricolore_tutorial.Rmd#L132) gives an error
```
Error in titleGrob(label, x, y, hjust = hj, vjust = vj, angle = angle, : unused argument (expand_y = TRUE)
```

**Comment by tts** [comment]
If I'm not mistaken, in the vignette code example, either the order of `tric_dat` keys needs to be changed [here](https://github.com/rOpenGov/geofi/blob/master/vignettes/tricolore_tutorial.Rmd#L102) or ditto with the legend labs [here](https://github.com/rOpenGov/geofi/blob/master/vignettes/tricolore_tutorial.Rmd#L135) (probably the latter). As it is now, age groups `under_15` and `over64` are backwards.

**Comment by janikmiet** [comment]
@tts Good that you noticed! You are correct.
